### PR TITLE
Improve_Checkout_Model_Error_and_Notifications_(v0.6)

### PR DESCRIPTION
**Pull request by PedroDiez**
* Align Error structure
https://github.com/camaraproject/CarrierBillingCheckOut/issues/44

* Adding Notifications Model

* YAML v0.6 generated + documentation updated

* Changes in some parameters:
** merchant info is optional, but if included, at least merchant.id is required
** order.id is set to optional

NOTE:
* pattern: '^[4-5][0-9]{2}$' -> has to be removed. Noted for a next version

### CODE REVIEW

**Review by bigludo7 — COMMENTED** [review]
Pedro, I have error when I copy/paste the definition on https://editor.swagger.io/
Could you take a look please?

**Comment by PedroDiez** [comment]
Thanks Ludovic! yes it seems some errors, i need to check in detail

**Review by bigludo7 — COMMENTED** [review]
You mention in the swagger:
`This resource has one operation to send events to the notification_url, when provided by the API client in the purchase creation.`

But the purchase data structure did not features this notification_url attribute.

Is it on purpose (to be updated later) or not? 
Thanks

**Comment by PedroDiez** [comment]
> You mention in the swagger: `This resource has one operation to send events to the notification_url, when provided by the API client in the purchase creation.`
> 
> But the purchase data structure did not features this notification_url attribute.
> 
> Is it on purpose (to be updated later) or not? Thanks

Thanks Ludovic, yes i missed to indcate the param. Already made a commit to fix it
I am going to also check optionality of some parameters in this proposal taking advantage of it, based on open questions issue.

**Review by bigludo7 — APPROVED** [review]
Look good for me !

**Comment by PedroDiez** [comment]
Thanks for the review. Merging it

**Pull request merged**
