### PR TITLE
Api spec fixes from linter rules

### LINKED ISSUE #126: Implement use of linting rule set for Carrier Billing API
**Problem description**
Implement use of linting rule set for Carrier Billing API.
what we have to do is well documented in Commonalities:
https://github.com/camaraproject/Commonalities/pull/110
https://github.com/camaraproject/Commonalities/pull/74

**Expected action**
Check our API with linting rule set
provide feedback to commonalities team

**Additional context**
cc: @rartych who asked project volunteer to perform this action.

### PR DESCRIPTION
**Pull request by PedroDiez**
#### What type of PR is this?

* correction

#### What this PR does / why we need it:

PR to fix some API spec format considerations from linter rules:
- response codes between quotes marks
- "status" within Error Info model is an integer, as per commonalities.

PR created over release-0.2.0 branch in order to incorporate to it before merging

#### Which issue(s) this PR fixes:

Fixes #126

### CODE REVIEW

**Comment by PedroDiez** [comment]
Going to close and generate a new one considering the linter rules output

**Comment by PedroDiez** [comment]
Have make some tests but seems there is no way currently to modify "release" branch as current config

**Comment by PedroDiez** [comment]
Please @bigludo7, @rartych take a look to this PR first in order to merge and after that I will synchornize the release one:
https://github.com/camaraproject/CarrierBillingCheckOut/pull/134

**Review by bigludo7 — APPROVED** [review]
LGTM

**Pull request merged**
