### PR TITLE
Release 0.3.0-rc.1

### LINKED ISSUE #164: Generate Release Candidate Carrier Billing versions for Meta Release v0.4 - Fall24
**Problem description**
Generate Release candidate Carrier Billing versions for:
- Carrier Billing Payment: v0.3.0-rc.1
- Carrier Billing Refund: v0.1.0-rc.1

**Expected action**
Generate PR with expected actions as per Release Management and Commonalities Guidelines  

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by PedroDiez**
#### What type of PR is this?

Add one of the following kinds:
* documentation
* subproject management

#### What this PR does / why we need it:

Generation of first release-candidate for Carrier Billing APIs Family

This first release candidate r0.3.0-rc.1 contains the definition and documentation of
* Carrier Billing v0.3.0-rc.1
* Carrier Billing Refund v0.1.0-rc.1

The API definition(s) are based on
* Commonalities v0.4.0
* Identity and Consent Management v0.2.0

#### Which issue(s) this PR fixes:

Fixes #164

#### Special notes for reviewers:

N/A

#### Changelog input

```
 Carrier Billing Release 0.4.0-rc.1

```

#### Additional documentation 

N/A

### CODE REVIEW

**Comment by rartych** [comment]
@PedroDiez  Please note that Release Management decided on decoupling of release numbering from API version numbering.:
https://wiki.camaraproject.org/display/CAM/API+Release+Process#APIReleaseProcess-APIreleasenumbering

Please look also at: [CHANGELOG_TEMPLATE.md](https://github.com/camaraproject/ReleaseManagement/blob/main
/documentation/CHANGELOG_TEMPLATE.md) and [CHANGELOG_EXAMPLE.md](https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/CHANGELOG_EXAMPLE.md)

**Comment by PedroDiez** [comment]
> @PedroDiez Please note that Release Management decided on decoupling of release numbering from API version numbering.: https://wiki.camaraproject.org/display/CAM/API+Release+Process#APIReleaseProcess-APIreleasenumbering
> 
> Please look also at: [CHANGELOG_TEMPLATE.md](https://github.com/camaraproject/ReleaseManagement/blob/main /documentation/CHANGELOG_TEMPLATE.md) and [CHANGELOG_EXAMPLE.md](https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/CHANGELOG_EXAMPLE.md)

Many thanks Rafal! I will check this accordingly

**Comment by hdamker** [comment]
@PedroDiez Should I delete this (protected) branch (to clean up)? BTW: only branches with the pattern "*release*" are protected ... something which we will not use anymore going forward.

**Comment by PedroDiez** [comment]
> Should I delete this (protected) branch (to clean up)? BTW: only branches with the pattern "*release*" are protected ... something which we will not use anymore going forward.

Thanks Herbert, I think it is not required. No blocker for the WG activity. And yes, after checking with Rafal few weeks ago release branches will no longer be using.

**Comment by hdamker** [comment]
@PedroDiez I renamed the branch to obsolete-0.3.0-rc.1 so that no-one is confused by it and you can delete yourself. It would btw make sense to clean-up the about 80 branches within the repository ... normally most of them should have been in personal forks as we are following the "fork and pull" model (cf. https://github.com/camaraproject/Governance/blob/main/CONTRIBUTING.md). But first the release, then the clean-up.

**Comment by PedroDiez** [comment]
Ok take note of this task to be done in future

**Pull request closed without merging**
