### PR TITLE
Add a business scenario slide

### PR DESCRIPTION
**Pull request by ShutingQing**
Add a business scenarion slide, basically try to explain to people Carrier Billing Check Out API's value. Why they should use the api for the checkout and payment function, instead of developing their own.

### CODE REVIEW

**Comment by ShutingQing** [comment]
> Probably need to be discussed during next CarrierBillingCheckOut meeting. I'm not sure how 'business' related documentation should be now managed as we moved to integrate documentation within API OAS definition.
> 
> WDYT @PedroDiez?

Sure, no problem we can discuss. :)  BTW, we have a weekly meeting today or next Wed? @PedroDiez @bigludo7

**Comment by bigludo7** [comment]
@ShutingQing : Next Wed (May 24th).

**Comment by ShutingQing** [comment]
> @ShutingQing : Next Wed (May 24th).

Okay, thanks

**Comment by PedroDiez** [comment]
Yes, usually before making PR it is commonly to generate an issue in order to debate/discuss on the topic

**Comment by ShutingQing** [comment]
> usually

Ok, got it. We can discuss it on next meeting. And then to see whether we need this PR or modify or something.

**Comment by ShutingQing** [comment]
cbco business scenario

@bigludo7 @PedroDiez Hi Ludovic, Pedro, please take a look, WDYT

**Comment by bigludo7** [comment]
Hi @ShutingQing 
Thanks for that.
I appreciate the contribution but as I have stated previously I'm not sure about business documentation as we are working on API definition.

**Comment by PedroDiez** [comment]
Hi @ShutingQing I think this is more for the GSMA OGW Carrier Billing Track

**Comment by ShutingQing** [comment]
Welcome for the contribution. :) 
Cuz now CAMARA is getting hotter, I believe more and more end users will come here for infos than OPW. CAMARA github is a more straight forward place for new comers. Like in many places, people use credit card, QR code to pay. So for app developers, hardly can they realize why they need call operators' API, even they have to pay for this. So i think it's a good time to give them an idea here at their first glance.

**Comment by PedroDiez** [comment]
Hi @ShutingQing,

Understand you comment, however that is information suited for GSMA OGW because at that level is where such a business information can be managed and adapted to provide the suitable business message.

That is managed in GSMA, you can ping Gareth Williams for that aim

**Pull request closed without merging**
